/**
 * QirPreview.tsx — Interactive Live QIR (Quantum Intermediate Representation) Preview.
 * Displays QIR 1.0 LLVM IR runtime calls generated by QLLVM co-compilation.
 */

import React, { useState, useMemo } from "react";
import { Copy, Check, Download, Terminal, Layers, FileCode2, Eye, Sparkles } from "lucide-react";
import { QIR_INTRINSIC_MAP, InstOp } from "../sim/qllvmEngine";

interface QirPreviewProps {
  qirLines: string[];
  ops: InstOp[];
  numQubits: number;
  swapsInserted?: number;
}

export const QirPreview: React.FC<QirPreviewProps> = ({
  qirLines,
  ops,
  numQubits,
  swapsInserted = 0,
}) => {
  const [viewMode, setViewMode] = useState<"clean" | "annotated" | "intrinsics">("clean");
  const [copied, setCopied] = useState<boolean>(false);
  const [filterQuery, setFilterQuery] = useState<string>("");

  // Categorize intrinsics inventory
  const intrinsicStats = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const line of qirLines) {
      const match = line.match(/@(__quantum__\w+)/);
      if (match) {
        const name = match[1];
        counts[name] = (counts[name] || 0) + 1;
      }
    }
    return counts;
  }, [qirLines]);

  // Generate annotated QIR lines
  const annotatedLines = useMemo(() => {
    const lines: string[] = [
      `; ModuleID = 'qllvm_module'`,
      `; Source: OpenQASM 2.0 -> MLIR Quantum Dialect -> QIR 1.0 Lowering`,
      `; Target Hardware: IBM Falcon 27Q Heavy-Hex (SABRE Lookahead Guided)`,
      `; Total Physical Qubits Allocated: ${Math.max(numQubits, 5)}`,
      `; SWAP Intrinsics Injected: ${swapsInserted}`,
      ``,
      `%Array = type opaque`,
      `%Qubit = type opaque`,
      `%Result = type opaque`,
      ``,
      `declare %Array* @__quantum__rt__qubit__allocate_array(i64)`,
      `declare void @__quantum__rt__qubit_release_array(%Array*)`,
      `declare %Qubit* @__quantum__rt__array_get_element_ptr(%Array*, i64)`,
      `declare void @__quantum__qis__h(%Qubit*)`,
      `declare void @__quantum__qis__x(%Qubit*)`,
      `declare void @__quantum__qis__z(%Qubit*)`,
      `declare void @__quantum__qis__rz(double, %Qubit*)`,
      `declare void @__quantum__qis__cx(%Qubit*, %Qubit*)`,
      `declare void @__quantum__qis__swap(%Qubit*, %Qubit*)`,
      `declare %Result* @__quantum__qis__mz(%Qubit*)`,
      ``,
      `define void @quantum_main() #0 {`,
      `entry:`,
    ];

    for (let i = 0; i < qirLines.length; i++) {
      const l = qirLines[i];
      if (l.startsWith(";")) continue;
      lines.push(`  ${l}`);
    }

    lines.push(`  ret void`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`attributes #0 = { "quantum.circuit" = "true" "qir.version" = "1.0" }`);
    return lines;
  }, [qirLines, numQubits, swapsInserted]);

  const displayedContent = useMemo(() => {
    if (viewMode === "annotated") return annotatedLines.join("\n");
    return qirLines.join("\n");
  }, [viewMode, annotatedLines, qirLines]);

  const filteredLines = useMemo(() => {
    const raw = viewMode === "annotated" ? annotatedLines : qirLines;
    if (!filterQuery) return raw;
    return raw.filter(l => l.toLowerCase().includes(filterQuery.toLowerCase()));
  }, [viewMode, annotatedLines, qirLines, filterQuery]);

  const handleCopy = () => {
    navigator.clipboard.writeText(displayedContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (format: "ll" | "qir") => {
    const blob = new Blob([displayedContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `qllvm_output.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 flex flex-col gap-3">
      {/* Header bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-3">
        <div className="flex items-center gap-2">
          <Terminal className="w-4 h-4 text-cyan-400" />
          <span className="text-xs font-semibold text-slate-200 font-mono uppercase tracking-wider">
            Live QIR Preview (QIR 1.0 Specification)
          </span>
          <span className="bg-cyan-950 text-cyan-300 border border-cyan-800/80 px-2 py-0.5 rounded text-[10px] font-mono font-medium">
            {qirLines.length} Instructions
          </span>
        </div>

        {/* View Mode controls */}
        <div className="flex items-center gap-1.5">
          <div className="flex items-center bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs font-mono">
            <button
              onClick={() => setViewMode("clean")}
              className={`px-2.5 py-1 rounded transition-colors cursor-pointer ${
                viewMode === "clean"
                  ? "bg-cyan-500 text-slate-950 font-bold"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              Clean QIR
            </button>
            <button
              onClick={() => setViewMode("annotated")}
              className={`px-2.5 py-1 rounded transition-colors cursor-pointer ${
                viewMode === "annotated"
                  ? "bg-cyan-500 text-slate-950 font-bold"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              Full LLVM Module (.ll)
            </button>
            <button
              onClick={() => setViewMode("intrinsics")}
              className={`px-2.5 py-1 rounded transition-colors cursor-pointer ${
                viewMode === "intrinsics"
                  ? "bg-cyan-500 text-slate-950 font-bold"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              Intrinsics Summary
            </button>
          </div>

          {/* Action buttons */}
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-md transition-colors cursor-pointer font-mono border border-slate-700/60"
            title="Copy QIR to clipboard"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{copied ? "Copied" : "Copy"}</span>
          </button>

          <button
            onClick={() => handleDownload("ll")}
            className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-cyan-300 hover:text-white bg-cyan-950/80 hover:bg-cyan-900 border border-cyan-800/80 rounded-md transition-colors cursor-pointer font-mono"
            title="Export as .ll (LLVM IR)"
          >
            <Download className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Export .ll</span>
          </button>
        </div>
      </div>

      {/* Intrinsics Overview Cards (shown when intrinsics mode or as header) */}
      {viewMode === "intrinsics" ? (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-950 p-4 rounded-lg border border-slate-800 font-mono text-xs">
          {Object.entries(intrinsicStats).map(([name, count]) => (
            <div key={name} className="flex flex-col gap-0.5 bg-slate-900/60 p-2.5 rounded border border-slate-800">
              <span className="text-[10px] text-slate-500 truncate" title={name}>
                {name.replace("__quantum__", "")}
              </span>
              <span className="text-base font-bold text-cyan-300">{count} calls</span>
            </div>
          ))}
        </div>
      ) : (
        /* Code Preview Area */
        <div className="relative flex flex-col">
          {/* Quick filter input */}
          <div className="flex items-center justify-between mb-2">
            <span className="text-[11px] text-slate-400 font-mono">
              Lowering Target: <strong className="text-cyan-400">@__quantum__qis__*</strong> intrinsics
            </span>
            <input
              type="text"
              placeholder="Filter QIR lines..."
              value={filterQuery}
              onChange={e => setFilterQuery(e.target.value)}
              className="bg-slate-950 border border-slate-800 text-[11px] font-mono text-slate-300 rounded px-2.5 py-0.5 focus:outline-none focus:border-cyan-500 w-44"
            />
          </div>

          <div className="bg-slate-950 rounded-lg border border-slate-800 p-3 max-h-[380px] overflow-y-auto overflow-x-auto font-mono text-xs select-text">
            {filteredLines.map((line, idx) => {
              const isComment = line.trim().startsWith(";");
              const isCall = line.includes("call void") || line.includes("call %");
              const isAlloc = line.includes("allocate_array");
              const isRelease = line.includes("release_array");
              const isSwap = line.includes("__quantum__qis__swap");
              const is2Q = line.includes("__quantum__qis__cx");

              return (
                <div
                  key={idx}
                  className={`flex gap-3 px-1 py-0.5 rounded leading-relaxed hover:bg-slate-900/70 transition-colors ${
                    isSwap
                      ? "bg-amber-500/10 text-amber-200"
                      : isAlloc || isRelease
                      ? "text-purple-300"
                      : isComment
                      ? "text-slate-500 italic"
                      : is2Q
                      ? "text-cyan-300"
                      : "text-slate-200"
                  }`}
                >
                  <span className="text-slate-600 select-none text-right w-8 shrink-0 text-[11px]">
                    {idx + 1}
                  </span>
                  <span className="break-all whitespace-pre font-mono">
                    {/* Syntax highlight simulation */}
                    {line}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Footer info badge */}
      <div className="flex flex-wrap items-center justify-between text-[11px] text-slate-400 font-mono pt-1">
        <span className="flex items-center gap-1.5">
          <span className="w-2 h-2 rounded-full bg-emerald-400 inline-block" />
          <span>Lowering Stage: MLIR quantum dialect lowered to LLVM QIR runtime spec 1.0</span>
        </span>
        <span className="text-slate-500">
          Target Spec: <strong className="text-slate-300">QIR Alliance 1.0 (QCFlow)</strong>
        </span>
      </div>
    </div>
  );
};
