/**
 * QirView.tsx — Dedicated Full-Screen QIR 1.0 Preview & Analysis Workspace.
 * Demonstrates lowering from OpenQASM 2.0 to LLVM IR with QIR 1.0 intrinsics.
 */

import React, { useState, useMemo } from "react";
import { QIR_INTRINSIC_MAP, QLLVMCompiler, CouplingGraph, ibm27FalconTopology } from "../sim/qllvmEngine";
import { generateQftQasm, generateGhzQasm, generateToffoliChainQasm } from "../sim/topologyCompare";
import { SAMPLE_DEFAULT_QASM } from "../sim/masterReports";
import { QirPreview } from "./QirPreview";
import { FileCode2, Sliders, Sparkles, BookOpen, Layers } from "lucide-react";

export const QirView: React.FC = () => {
  const [selectedCircuit, setSelectedCircuit] = useState<"default" | "qft" | "ghz" | "toffoli">("default");
  const [lookahead, setLookahead] = useState<number>(4);

  const cg = useMemo(() => new CouplingGraph(ibm27FalconTopology()), []);

  const qasmCode = useMemo(() => {
    switch (selectedCircuit) {
      case "qft": return generateQftQasm(5);
      case "ghz": return generateGhzQasm(5);
      case "toffoli": return generateToffoliChainQasm(5);
      default: return SAMPLE_DEFAULT_QASM;
    }
  }, [selectedCircuit]);

  const report = useMemo(() => {
    const compiler = new QLLVMCompiler(cg, 5);
    return compiler.compile(qasmCode, true, lookahead);
  }, [qasmCode, cg, lookahead]);

  return (
    <div className="flex flex-col gap-6 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl md:text-2xl font-bold tracking-tight text-white font-display">
              QIR 1.0 Interactive Preview &amp; Specification
            </h1>
            <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800/80">
              QIR v1.0 / LLVM 12
            </span>
          </div>
          <p className="text-xs md:text-sm text-slate-400 mt-1 max-w-3xl">
            Live LLVM IR lowerings with QIR runtime (@__quantum__rt__*) and quantum instruction set (@__quantum__qis__*) intrinsics
            generated by QLLVM with SABRE lookahead routing on the IBM Falcon 27Q QPU.
          </p>
        </div>

        {/* Circuit Selector */}
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400 font-mono">Circuit:</span>
          {(
            [
              { id: "default", label: "Bell + Toffoli" },
              { id: "qft", label: "QFT(5)" },
              { id: "ghz", label: "GHZ(5)" },
              { id: "toffoli", label: "Toffoli Chain" },
            ] as const
          ).map(c => (
            <button
              key={c.id}
              onClick={() => setSelectedCircuit(c.id)}
              className={`px-2.5 py-1 text-xs rounded font-mono transition-colors cursor-pointer border ${
                selectedCircuit === c.id
                  ? "bg-cyan-500/20 text-cyan-300 border-cyan-500/50 font-semibold"
                  : "bg-slate-900 text-slate-400 border-slate-800 hover:text-white"
              }`}
            >
              {c.label}
            </button>
          ))}
        </div>
      </div>

      {/* Main QIR Component */}
      <QirPreview
        qirLines={report.qir_ir}
        ops={report.stage_gates.routed}
        numQubits={5}
        swapsInserted={report.swaps_inserted}
      />
    </div>
  );
};
